// libs/cart/feature-main/src/lib/main.tsx
import './main.module.scss';
import {
  CartItem,
  cartService,
} from '@angular-with-react-micro-frontends-example/shared/data-access-cart';

import * as React from 'react';

export class Main extends React.PureComponent {
  override state: { cartItems: CartItem[] } = { cartItems: [] };

  removeCartItem = (id: number) => {
    cartService.removeItem(id);
  };

  override componentDidMount() {
    cartService.cartItems$.subscribe((cartItems) => {
      this.setState({ cartItems });
    });
  }

  override render() {
    const noCartItems = <p>No cart items</p>;

    const cartItems = this.state.cartItems.map(({ id, product, amount }) => {
      return (
        <div>
          <h3>{product.title}</h3>
          <img height="100px" src={product.image} alt={product.title} />
          <p>Amount: {amount}</p>
          <button onClick={() => this.removeCartItem(id)}>Remove item</button>
        </div>
      );
    });

    return (
      <div>{this.state.cartItems.length === 0 ? noCartItems : cartItems}</div>
    );
  }
}

export default Main;

// libs/products/feature-main/src/lib/main.component.ts
import { cartService } from '@angular-with-react-micro-frontends-example/shared/data-access-cart';
import {
  Product,
  productsService,
} from '@angular-with-react-micro-frontends-example/shared/data-access-products';
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';

@Component({
  selector: 'products-main',
  templateUrl: './main.component.html',
  styleUrls: ['./main.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MainComponent implements OnInit {
  loading$ = productsService.loading$;
  products$ = productsService.products$;

  ngOnInit(): void {
    productsService.loadProducts().then();
  }

  addItem(product: Product): void {
    cartService.addItem(product);
  }
}

<ng-container>
  <ng-container *ngIf="loading$ | async as loading">
    <p>Loading products...</p>
  </ng-container>
  <ng-container *ngIf="products$ | async as products">
    <ng-container *ngIf="products.length > 0">
      <ng-container *ngFor="let product of products">
        <h2>{{ product.title }}</h2>
        <button (click)="addItem(product)">Add to cart</button>
      </ng-container>
    </ng-container>
  </ng-container>
</ng-container>
